filter:
  paths:
    - src/main/java/
build:
  nodes:
    analysis:
      environment:
        docker:
          remote_engine: true
  environment:
    sdkman:
      - java 17.0.4-amzn
checks:
  java:
    code_rating: true